### PR TITLE
Updated README with instructions for testing

### PR DESCRIPTION
**Pull request by dbernar1**
Here's the README version for dealing with tmp/cache as suggested.

### CODE REVIEW

**Comment by amirci** [comment]
I thought you have to run 

```
rake db:test:prepare
```

In order to setup the test database....

**Comment by swalberg** [comment]
That might have been my fault. Out of habit I do the migrations rather than db:test:prepare.

That said, if we use Dan's other PR to add rspec-rails to the development group, running `bundle exec rake rspec` will do both the test:prepare and the tests itself.

**Comment by dbernar1** [comment]
Thanks. I've updated to rake db:test:prepare.

**Comment by amirci** [comment]
Actually you need to do first a 

```
rake db:migrate
```

And then do the prepare, otherwise **schema.rb** won't be updated

**Comment by dbernar1** [comment]
Thanks. I've added that step and this time I confirmed that a fresh clone can test by following those instructions.

**Pull request merged**
