### PR TITLE
Set up Vagrant for winnivote

### PR DESCRIPTION
**Pull request by swalberg**
Thought this might help some of the UNIX shy people get up and going with the app.
- Use Ubuntu 12.04 Precise Pangolin base box
- Provision a basic box with chef-solo
- Install some helpful sysadmin tools
- Modify Gemfile to use sqlite3
- Add instructions to README

### CODE REVIEW

**Comment by swalberg** [comment]
Would appreciate it if someone tries this out. It's possible you might need to do a `git submodule init` after cloning the repo, which I didn't put in the instructions.

**Comment by stungeye** [comment]
I'll test out the Vagrant / Chef process and let you know how it goes!

**Comment by amirci** [comment]
Perhaps we need to add rvm with the ruby version....... and have bundler
installed etc...

**Comment by swalberg** [comment]
In the VM? I used rbenv and install `bundler` and `foreman`. See https://github.com/winnipegrb/winnivote/blob/master/chef/roles/development.rb

**Comment by amirci** [comment]
I'm fine w that... I'll try again... I don't think it worked.....

**Comment by swalberg** [comment]
Is chef completing successfully?

Sean

On Mon, Oct 7, 2013 at 10:28 AM, Amir Barylko notifications@github.comwrote:

> I'm fine w that... I'll try again... I don't think it worked.....
> 
> On Mon, Oct 7, 2013 at 10:07 AM, Sean Walberg notifications@github.comwrote:
> 
> > In the VM? I used rbenv and install bundler and foreman. See
> > 
> > https://github.com/winnipegrb/winnivote/blob/master/chef/roles/development.rb
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/winnipegrb/winnivote/pull/2#issuecomment-25816262>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/winnipegrb/winnivote/pull/2#issuecomment-25818186
> .

## 

Sean Walberg sean@ertw.com    http://ertw.com/

**Comment by stungeye** [comment]
I got the following error after running "vagrant up". This was on my work Windows 7 laptop. I'm pretty sure I've messed something up on my end 'though, cause this error isn't specific to just your Vagrantfile. I wonder what I changed on this system? Any ideas?

[start up lines snipped]

[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.6.7/lib/net/ssh/authentication/agent/socket.rb:81:in `negotiate!': unknown response from agent: 1, "\x00\x00\x00-\x01\x00\x00\x00(SSH-2.0-Ruby/Net::SSH_2.6.7 i386-mingw32" (Net::SSH::Authentication::AgentError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.6.7/lib/net/ssh/authentication/agent/socket.rb:48:in`connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-2.6.7/lib/net/ssh/authentication/key_manager.rb:178:in `agent'

[many lines snipped]

```
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
```

**Comment by thetamind** [comment]
I'm running Vagrant 1.3.3 on Mac OS X 10.8 and Chef does not complete, failing on missing `build-essential` cookbook.

The source of the problem is submodules are not setup in the repo. After I clone I do not have a `.gitmodules` file.

```
    $ git submodule init
    No submodule mapping found in .gitmodules for path 'chef/cookbooks/build-essential'
```

You can see GitHub does not display submodule links for the [chef cookbook folders](https://github.com/winnipegrb/winnivote/tree/8cabd804ede7e014873429c0f145bdfd745d091f/chef/cookbooks).

Git submodules are tricky. Try [git subtree](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) instead.

FYI: [Rove](http://rove.io/) is a neat Vagrant/Chef config generator for development.

**Comment by stungeye** [comment]
I was able to get past my SSH error (it turned out to be a conflict with [Pageant](https://github.com/net-ssh/net-ssh/issues/92)), however I then got the same "missing build-essential cookbook" error mentioned above.

**Comment by swalberg** [comment]
@thetamind Hm, I'm not sure how to generate the .gitmodules file. I can see I don't have one, I just cloned the repos inside mine.

**Comment by thetamind** [comment]
@swalberg Just cloning them into a subfolder won't work. GitHub is displaying them as submodule because it detects the nested `.git` folders. But git has no mapping to the original repos if you don't use the `git submodule` commands. And will not include their contents in the repo. [Documentation](http://git-scm.com/book/en/Git-Tools-Submodules).

Here's how to update a cookbook to a submodule:

```
$ git rm chef/cookbooks/build-essential
$ git submodule add https://github.com/opscode-cookbooks/build-essential.git chef/cookbooks/build-essential
$ git add .gitmodules
$ git status
```

Repeat for each cookbook.

**Comment by swalberg** [comment]
Thanks Matt, I'll fix it up shortly.

**Comment by swalberg** [comment]
@stungeye @thetamind Can either or both of you try cloning https://github.com/swalberg/winnivote and using the `vagrant` branch? Then run `git submodule update --init --recursive` after.

Thanks

**Comment by stungeye** [comment]
I cloned that repo, checked out the vagrant branch, and ran the git submodules command. I then ran vagrant up. Everything went well until just after rbenv installed:

```
Error executing action `install` on resource 'rbenv_gem[2.0.0-p247::bundler] (system)'
```

This is followed by a cookbook trace that references:

```
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/libraries/chef_rbenv_mixin.rb:30:in `shell_out!'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/libraries/chef_provider_package_rbenvrubygems.rb:66:in `install_package'
```

I can still ssh to the virtual machine, however the gem list seems incomplete:

```
vagrant@precise64:~$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
io-console (0.4.2)
json (1.7.7)
minitest (4.3.2)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
test-unit (2.0.0.0)
```

**Comment by swalberg** [comment]
Can you gist the whole error, and possibly the `stacktrace.out` file on the vm that gets referenced please?

**Comment by stungeye** [comment]
I don't have time atm to rerun the vagrant up process (it took almost 15 minutes to get to the error) but here is [the chef-stacktrace.out file](https://gist.github.com/stungeye/6921189).

**Comment by swalberg** [comment]
No worries. Looks like the "bundle install" command timed out. Transient
network error? Firewall? DNS?

On Thu, Oct 10, 2013 at 11:23 AM, Kyle Geske notifications@github.comwrote:

> I don't have time atm to rerun the vagrant up process (it took almost 15
> minutes to get to the error) but here is the chef-stacktrace.out filehttps://gist.github.com/stungeye/6921189
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/winnipegrb/winnivote/pull/2#issuecomment-26068445
> .

## 

Sean Walberg sean@ertw.com    http://ertw.com/

**Comment by stungeye** [comment]
I am behind a fairly restrictive RRC firewall, but I don't have any problem running bundle install from my (non-VM) machine. Maybe @thetamind can test out this new branch as well.

**Comment by thetamind** [comment]
It works (8 minutes). The slowest part is installing ruby from source. Just resume provisioning to save time: `vagrant provision`.

```
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.3.5)
dotenv (0.9.0)
foreman (0.63.0)
io-console (0.4.2)
json (1.7.7)
minitest (4.3.2)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
test-unit (2.0.0.0)
thor (0.18.1)
```

Bundler vendored the project gems so they are not in the global list.

Binstubs are not enabled, so to start the server `cd /vagrant && bundle exec rails s`

**Pull request merged**
