### PR TITLE
Perceived enhancements to the sign up feature specs

### PR DESCRIPTION
**Pull request by dbernar1**
Hi. I think I've now finally rebased this properly, and squashed the commits. Sorry about any inconvenience.

Please let me know if anything else needs to be done if you'd like to merge this in.

### CODE REVIEW

**Comment by swalberg** [comment]
As before I'm :+1: on this knowing there's some improvements to be made.

@dbernar1 FYI you don't have to open a new pull request. The PR is tied to the branch, when you `git push -f origin mybranch` your branch the PR will be updated. Since you did your work in `master` I can see how the rebase might have been a bit tricky though.

**Comment by dbernar1** [comment]
Thank you. I think I did not understand what is a good way to collaborate with you yesterday on further ways of making the tests better ( the "knowing there's some improvements to be made", as you say ), but I think I've figured that out a bit, so I'd like to give that another go now, if you're still game.

**Here's the list of issues you brought up so far:**

> 1. While the output of rspec is better, some of the code doesn't read well anymore. e.g. it "they end up on the home page of the site" do
> 2. Rather than visit somehelper and checking for the existence of link with href of helper, shouldn't the test focus more on what the user sees? That is, instead of going to the registration page by specifying the helper, what about: `
>    visit '/';
>    click_link 'Sign up'`
> 3. Rspec custom matcher instead of confirm_these_possible_signup_failure_cases_are_handled()

**Here's where I'm at with regard to those:**
1. I've spent a fair amount of time trying to re-word the string parameters to it() and context(), and I have not yet arrived at something that is both fluent in the tests and still preserves the fluent `--format documentation output`. My decision for a trade-off here would be to take good `--format documentation` output over fluent test code, until I reach a state in which both goals are met. I presume that you're viewing it similarly, based on the fact that you're giving the :+1: . Is that about right?
2. I had replied with something along the lines that: the fact that you can arrive at the signup page by clicking a link labeled 'Sign up' on the home page seems to belong more in the spec of the home page functionality, while the fact that the system provides a path at which the signup page can be accessed belongs in the spec of the sign up functionality. What do you think of that reasoning? Have you considered that before?
3. Thanks for that tip. I think I see a way to implement that which I would like, so I will look at implementing that and let you know what I find.

PR-wise: I hope I might get a chance to learn how to avoid a new PR at the next opportunity...unless there's a way for me to get practice with that now, so please let me know if you know how I could go about that.

**Comment by swalberg** [comment]
Dan,
1. Yes I agree.
2. We're not testing a page or controller as much as we are testing a flow. What you have now is valid. I'm just offering advice that if I were doing it, I'd be testing the whole flow starting from "User hits home page". Often feature specs are the things that let you know that someone accidentally dropped a link or broke a button.
3. Sounds good.

As for the PR, just keep committing to this branch and you'll see the PR updated with the new commits every time you `git push`. After it's good, you can `rebase -i` then `push -f` and the PR will update again, but with one commit.

What you did before was a PR to merge your master into winnivote/master. So to squash the commits it's a bit more complicated. You almost always want to be working on a branch.

**Comment by dbernar1** [comment]
The newest code features a change in the spec/features/support/signup.rb file, to wrap the functions in a module.

This now works, since I've removed confirm_these_possible_signup_failure_cases_are_handled(), which I've in-lined again into the spec file. That seems to be the best solution to me at this time.

I've also adjusted how confirming there is a way for the user to get to the sign in page from the sign up page, which is my current preferred way of expressing the functionality discussed in point 2.

**Comment by amirci** [comment]
We should implement the test using page objects. Let's coordinate and do that.

**Pull request closed without merging**
