### PR TITLE
Vagrant redux - set up submodules

### PR DESCRIPTION
**Pull request by swalberg**
Submodules set up properly, thanks @thetamind

### CODE REVIEW

**Comment by stungeye** [comment]
It should be noted that when using vagrant I still need to run the following after clone the repo, and before running `vagrant up`:

```
git submodule update --init --recursive
```

**Comment by swalberg** [comment]
Yes, I believe #3 has an update to the docs

**Comment by stungeye** [comment]
Cool. Also, during the Chef setup I'm now getting this error:

```
================================================================================
Error executing action `install` on resource 'package[git-core]'
================================================================================

Chef::Exceptions::Exec
----------------------
apt-get -q -y install git-core=1:1.7.9.5-1 returned 100, expected 0
```

Googling around it seems that [the apt cookbook needs to be added](http://www.garysieling.com/blog/fixing-error-apt-get-return-100-expected-0-chefvagrant)?

**Comment by swalberg** [comment]
[This](https://github.com/winnipegrb/winnivote/blob/master/chef/cookbooks/winnivote/recipes/default.rb#L7) should have taken care of that :(

**Pull request merged**
